server:
  port: 8090    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
  jpa:
    show-sql: true
 

management:
  endpoints:
    web:
      exposure:
        include: "*"
        

message: The Service is up and running, dynamic 1!
cloudConfigMsg: I am coming from Spring Cloud Config!!


