server:
  port: 8090    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/org
    username: root
    password: sqlPass@22



  jpa:
    show-sql: true
   # databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
message: The Service is up and running, dynamic!

