server:
  port: 8090    
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/org
    username: ${user.name}
    password: ${user.password}



  jpa:
    show-sql: true
 

management:
  endpoints:
    web:
      exposure:
        include: "*"
        

message: The Service is up and running, dynamic 1!


